image: docker:latest

stages:
  - deploy

job_production:
  stage: deploy
  image: fajarfebriano/deployer-docker
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo $config >> ~/.ssh/config
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - dep deploy production -f deploy.php -vvv
  only:
    - master
